# Generated by Django 4.2.5 on 2024-01-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moodmatcher', '0002_post_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='community', max_length=20),
        ),
    ]
