# Generated by Django 4.2.5 on 2024-01-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moodmatcher', '0006_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/static/images/profile.png', upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
