# Generated by Django 4.2.5 on 2024-01-31 05:45

import Moodmatcher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moodmatcher', '0007_remove_profile_bio_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=Moodmatcher.models.default_profile_picture, upload_to='profile_pics/'),
        ),
    ]
