# Generated by Django 4.2.5 on 2024-01-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moodmatcher', '0005_uploadedimage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
