# Generated by Django 5.0.1 on 2024-01-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moodmatcher', '0009_post_likes_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Moodmatcher.post'),
        ),
    ]
