# Generated by Django 4.1 on 2024-02-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Moodmatcher",
            "0014_tourcategory_touretc_tourimgpath_tourinfo_tourkeyrat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
